package com.ecodeup.ws;

import javax.xml.ws.Endpoint;

//CON LA CLASE DEL MAIN PUBLICAMOS EL SERVICIO.
//CUANDO INICIE ESTA APP EN EL MAIN(), SE VA A CREAR EL EL WSDL, EL CONTRATO DONDE SE EXPONEN NUESTROS SERVICIOS DE WEBSERVICES. 


public class CalculadoraPublish {
	
	public static void main(String[]args) {
		//publish(DIRECCIÓN DONDE VAMOS A EXPONER EL SERVICIO, OBJ DE LA CLASE QUE IMPLEMENTA EL SERVICIO)
		//EN EL 1ER PARÁMETRO ES DONDE GENERARÁ EL WSDL.
		Endpoint.publish("http://localhost:1515/WS/Calculadora", new CalculadoraImpl());
		
		//DESPUÉS DE EJECUTAR LA CLASE DEL MAIN, HAY QUE IR AL BROWSER Y ESCRIBIR LO SIGUIENTE PARA VER EL WSDL:
		// http://localhost:1515/WS/Calculadora?wsdl
		
		
		//POSTERIORMENTE, PARA GENERAR AL CLIENTE USAMOS EL EXPLORADOR WINDOWS. VAMOS A LA CARPETA COM QUEES EL PAQUETE Q
		//..CONTIENE A LAS CLASES Y EN LA BARRA DE DIRECCIÓN ESCRIBIMOR CMD. CON ESTO SE ABRE LA CMD Y LE METEMOS ESTE COMANDO:
		//wsimport -s . http://localhost:1515/WS/Calculadora?wsdl
		
		
		//DESPUÉS CREAREMOS LA CLASE CON A QUE CONSUMIREMOS EL SERVICIO "CalculadoraConsumer" 
	}

}
